# Generated by Django 5.0.4 on 2024-04-22 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Date',
            new_name='Dates',
        ),
    ]
