# Generated by Django 5.0.4 on 2024-05-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='elapsed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='timer',
            name='running_since',
            field=models.IntegerField(null=True),
        ),
    ]
