# Generated by Django 5.0.4 on 2024-04-29 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.publisher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(auto_now_add=True, verbose_name='Date the book is published'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='Test', help_text='Title of the book', max_length=70),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(default='Az Hur', max_length=50),
        ),
    ]
