# Generated by Django 5.0.4 on 2024-05-03 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
