# Generated by Django 5.0.4 on 2024-04-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('published_date', models.DateTimeField()),
                ('summary', models.TextField()),
                ('company', models.CharField(max_length=35)),
                ('pages', models.IntegerField()),
            ],
        ),
    ]
